//autogenerated:yes
//nolint:revive,govet,errcheck
package ualberta

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_UALBERTA_AUTOPILOT_MODE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e UALBERTA_AUTOPILOT_MODE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := MODE_MANUAL_DIRECT.MarshalText()
		require.NoError(t, err)

		var dec UALBERTA_AUTOPILOT_MODE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, MODE_MANUAL_DIRECT, dec)
	})
}
