//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Obstacle distances in front of the sensor, starting from the left in increment degrees to the right
type MessageObstacleDistance = common.MessageObstacleDistance
