//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Temperature and humidity from hygrometer.
type MessageHygrometerSensor = common.MessageHygrometerSensor
