//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Report current used cellular network status
type MessageCellularStatus = common.MessageCellularStatus
