//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Reply to LOG_REQUEST_LIST
type MessageLogEntry = common.MessageLogEntry
