//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Request for terrain data and terrain status. See terrain protocol docs: https://mavlink.io/en/services/terrain.html
type MessageTerrainRequest = common.MessageTerrainRequest
