//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Orientation of a mount
type MessageMountOrientation = common.MessageMountOrientation
