//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// The IMU readings in SI units in NED body frame
type MessageHilSensor = common.MessageHilSensor
