//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Hardware status sent by an onboard computer.
type MessageOnboardComputerStatus = common.MessageOnboardComputerStatus
