//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ualberta

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Response from a PARAM_EXT_SET message.
type MessageParamExtAck = common.MessageParamExtAck
