//autogenerated:yes
//nolint:revive,govet,errcheck
package csairlink

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_AIRLINK_EYE_GS_HOLE_PUSH_RESP_TYPE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e AIRLINK_EYE_GS_HOLE_PUSH_RESP_TYPE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := AIRLINK_HPR_PARTNER_NOT_READY.MarshalText()
		require.NoError(t, err)

		var dec AIRLINK_EYE_GS_HOLE_PUSH_RESP_TYPE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, AIRLINK_HPR_PARTNER_NOT_READY, dec)
	})
}
