//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package csairlink

import (
	"fmt"
	"strings"
)

type AIRLINK_AUTH_RESPONSE_TYPE uint32

const (
	// Login or password error
	AIRLINK_ERROR_LOGIN_OR_PASS AIRLINK_AUTH_RESPONSE_TYPE = 0
	// Auth successful
	AIRLINK_AUTH_OK AIRLINK_AUTH_RESPONSE_TYPE = 1
)

var labels_AIRLINK_AUTH_RESPONSE_TYPE = map[AIRLINK_AUTH_RESPONSE_TYPE]string{
	AIRLINK_ERROR_LOGIN_OR_PASS: "AIRLINK_ERROR_LOGIN_OR_PASS",
	AIRLINK_AUTH_OK:             "AIRLINK_AUTH_OK",
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e AIRLINK_AUTH_RESPONSE_TYPE) MarshalText() ([]byte, error) {
	var names []string
	for mask, label := range labels_AIRLINK_AUTH_RESPONSE_TYPE {
		if e&mask == mask {
			names = append(names, label)
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *AIRLINK_AUTH_RESPONSE_TYPE) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask AIRLINK_AUTH_RESPONSE_TYPE
	for _, label := range labels {
		found := false
		for value, l := range labels_AIRLINK_AUTH_RESPONSE_TYPE {
			if l == label {
				mask |= value
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e AIRLINK_AUTH_RESPONSE_TYPE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
