//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Global position/attitude estimate from a vision source.
type MessageGlobalVisionPositionEstimate = common.MessageGlobalVisionPositionEstimate
