//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Control vehicle tone generation (buzzer).
type MessagePlayTune = common.MessagePlayTune
