//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Camera-IMU triggering and synchronisation message.
type MessageCameraTrigger = common.MessageCameraTrigger
