//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Vehicle status report that is sent out while orbit execution is in progress (see MAV_CMD_DO_ORBIT).
type MessageOrbitExecutionStatus = common.MessageOrbitExecutionStatus
