//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Message appropriate for high latency connections like Iridium
type MessageHighLatency = common.MessageHighLatency
