//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// The IMU readings in SI units in NED body frame
type MessageHighresImu = common.MessageHighresImu
