//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Request a data stream.
type MessageRequestDataStream = common.MessageRequestDataStream
