//autogenerated:yes
//nolint:revive,misspell,govet,lll
package cubepilot

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Provides state for additional features
type MessageExtendedSysState = common.MessageExtendedSysState
