//autogenerated:yes
//nolint:revive,govet,errcheck
package development

import (
	"testing"
)

func TestEnum_AIRSPEED_SENSOR_FLAGS(t *testing.T) {
	var e AIRSPEED_SENSOR_FLAGS
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
