//autogenerated:yes
//nolint:revive,govet,errcheck
package development

import (
	"testing"
)

func TestEnum_GPS_SPOOFING_STATE(t *testing.T) {
	var e GPS_SPOOFING_STATE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
