//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package development

import (
	"fmt"
	"strconv"
)

// The frame of a target observation from an onboard sensor.
type TARGET_OBS_FRAME uint32

const (
	// NED local tangent frame (x: North, y: East, z: Down) with origin fixed relative to earth.
	TARGET_OBS_FRAME_LOCAL_NED TARGET_OBS_FRAME = 0
	// FRD local frame aligned to the vehicle's attitude (x: Forward, y: Right, z: Down) with an origin that travels with vehicle.
	TARGET_OBS_FRAME_BODY_FRD TARGET_OBS_FRAME = 1
	// NED local tangent frame (x: North, y: East, z: Down) with an origin that travels with vehicle.
	TARGET_OBS_FRAME_LOCAL_OFFSET_NED TARGET_OBS_FRAME = 2
	// Other sensor frame for target observations neither in local NED nor in body FRD.
	TARGET_OBS_FRAME_OTHER TARGET_OBS_FRAME = 3
)

var labels_TARGET_OBS_FRAME = map[TARGET_OBS_FRAME]string{
	TARGET_OBS_FRAME_LOCAL_NED:        "TARGET_OBS_FRAME_LOCAL_NED",
	TARGET_OBS_FRAME_BODY_FRD:         "TARGET_OBS_FRAME_BODY_FRD",
	TARGET_OBS_FRAME_LOCAL_OFFSET_NED: "TARGET_OBS_FRAME_LOCAL_OFFSET_NED",
	TARGET_OBS_FRAME_OTHER:            "TARGET_OBS_FRAME_OTHER",
}

var values_TARGET_OBS_FRAME = map[string]TARGET_OBS_FRAME{
	"TARGET_OBS_FRAME_LOCAL_NED":        TARGET_OBS_FRAME_LOCAL_NED,
	"TARGET_OBS_FRAME_BODY_FRD":         TARGET_OBS_FRAME_BODY_FRD,
	"TARGET_OBS_FRAME_LOCAL_OFFSET_NED": TARGET_OBS_FRAME_LOCAL_OFFSET_NED,
	"TARGET_OBS_FRAME_OTHER":            TARGET_OBS_FRAME_OTHER,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e TARGET_OBS_FRAME) MarshalText() ([]byte, error) {
	name, ok := labels_TARGET_OBS_FRAME[e]
	if !ok {
		return nil, fmt.Errorf("invalid value %d", e)
	}
	return []byte(name), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *TARGET_OBS_FRAME) UnmarshalText(text []byte) error {
	value, ok := values_TARGET_OBS_FRAME[string(text)]
	if !ok {
		return fmt.Errorf("invalid label '%s'", text)
	}
	*e = value
	return nil
}

// String implements the fmt.Stringer interface.
func (e TARGET_OBS_FRAME) String() string {
	name, ok := labels_TARGET_OBS_FRAME[e]
	if !ok {
		return strconv.Itoa(int(e))
	}
	return name
}
