//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package development

import (
	"fmt"
	"strconv"
)

// Source of manual control input currently selected by the autopilot's manual control arbitration.
type MAV_MANUAL_INPUT_SOURCE uint64

const (
	// No manual input messages are currently being provided.
	MAV_MANUAL_INPUT_SOURCE_NONE MAV_MANUAL_INPUT_SOURCE = 0
	// Manual input messages are being provided by a radio control (RC) receiver.
	MAV_MANUAL_INPUT_SOURCE_RC MAV_MANUAL_INPUT_SOURCE = 1
	// Manual input messages are being provided by a MAVLink enabled input device (e.g. via MANUAL_CONTROL messages). The specific device is identified by the sender_system_id and sender_component_id fields.
	MAV_MANUAL_INPUT_SOURCE_MAVLINK MAV_MANUAL_INPUT_SOURCE = 2
	// Manual input messages are being provided simultaneously by both a radio control (RC) receiver and a MAVLink enabled input device.
	MAV_MANUAL_INPUT_SOURCE_MIXED MAV_MANUAL_INPUT_SOURCE = 3
)

var value_to_label_MAV_MANUAL_INPUT_SOURCE = map[MAV_MANUAL_INPUT_SOURCE]string{
	MAV_MANUAL_INPUT_SOURCE_NONE:    "MAV_MANUAL_INPUT_SOURCE_NONE",
	MAV_MANUAL_INPUT_SOURCE_RC:      "MAV_MANUAL_INPUT_SOURCE_RC",
	MAV_MANUAL_INPUT_SOURCE_MAVLINK: "MAV_MANUAL_INPUT_SOURCE_MAVLINK",
	MAV_MANUAL_INPUT_SOURCE_MIXED:   "MAV_MANUAL_INPUT_SOURCE_MIXED",
}

var label_to_value_MAV_MANUAL_INPUT_SOURCE = map[string]MAV_MANUAL_INPUT_SOURCE{
	"MAV_MANUAL_INPUT_SOURCE_NONE":    MAV_MANUAL_INPUT_SOURCE_NONE,
	"MAV_MANUAL_INPUT_SOURCE_RC":      MAV_MANUAL_INPUT_SOURCE_RC,
	"MAV_MANUAL_INPUT_SOURCE_MAVLINK": MAV_MANUAL_INPUT_SOURCE_MAVLINK,
	"MAV_MANUAL_INPUT_SOURCE_MIXED":   MAV_MANUAL_INPUT_SOURCE_MIXED,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e MAV_MANUAL_INPUT_SOURCE) MarshalText() ([]byte, error) {
	if name, ok := value_to_label_MAV_MANUAL_INPUT_SOURCE[e]; ok {
		return []byte(name), nil
	}
	return []byte(strconv.Itoa(int(e))), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *MAV_MANUAL_INPUT_SOURCE) UnmarshalText(text []byte) error {
	if value, ok := label_to_value_MAV_MANUAL_INPUT_SOURCE[string(text)]; ok {
		*e = value
	} else if value, err := strconv.Atoi(string(text)); err == nil {
		*e = MAV_MANUAL_INPUT_SOURCE(value)
	} else {
		return fmt.Errorf("invalid label '%s'", text)
	}
	return nil
}

// String implements the fmt.Stringer interface.
func (e MAV_MANUAL_INPUT_SOURCE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
