//autogenerated:yes
//nolint:revive,govet,errcheck
package development

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_GLOBAL_POSITION_SRC(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e GLOBAL_POSITION_SRC
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := GLOBAL_POSITION_UNKNOWN.MarshalText()
		require.NoError(t, err)

		var dec GLOBAL_POSITION_SRC
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, GLOBAL_POSITION_UNKNOWN, dec)
	})
}
