//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package development

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

type MAV_ODID_OPERATOR_ID_TYPE = common.MAV_ODID_OPERATOR_ID_TYPE

const (
	// CAA (Civil Aviation Authority) registered operator ID.
	MAV_ODID_OPERATOR_ID_TYPE_CAA MAV_ODID_OPERATOR_ID_TYPE = common.MAV_ODID_OPERATOR_ID_TYPE_CAA
)
