//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// File transfer protocol message: https://mavlink.io/en/services/ftp.html.
type MessageFileTransferProtocol = common.MessageFileTransferProtocol
