//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Winch status.
type MessageWinchStatus = common.MessageWinchStatus
