//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Speed estimate from a vision source.
type MessageVisionSpeedEstimate = common.MessageVisionSpeedEstimate
