//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// An ack for a LOGGING_DATA_ACKED message
type MessageLoggingAck = common.MessageLoggingAck
