//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// RTK GPS data. Gives information on the relative baseline calculation the GPS is reporting
type MessageGpsRtk = common.MessageGpsRtk
