//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Settings of a camera. Can be requested with a MAV_CMD_REQUEST_MESSAGE command.
type MessageCameraSettings = common.MessageCameraSettings
