//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Sets a desired vehicle position in a local north-east-down coordinate frame. Used by an external controller to command the vehicle (manual controller or other system).
type MessageSetPositionTargetLocalNed = common.MessageSetPositionTargetLocalNed
