//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// The global position resulting from GPS and sensor fusion.
type MessageUtmGlobalPosition = common.MessageUtmGlobalPosition
