//autogenerated:yes
//nolint:revive,misspell,govet,lll
package development

// Static characteristics of a distance sensor (onboard rangefinder).
// Measurements are sent in DISTANCE_SENSOR_V2.
type MessageDistanceSensorInfo struct {
	// Sensor ID. Matches the id field of DISTANCE_SENSOR_V2.
	Id uint8
	// Type of distance sensor.
	Type MAV_DISTANCE_SENSOR `mavenum:"uint8"`
	// Minimum distance the sensor can measure.
	MinDistance float32
	// Maximum distance the sensor can measure.
	MaxDistance float32
	// Direction the sensor faces.
	Orientation MAV_SENSOR_ORIENTATION `mavenum:"uint8"`
	// Horizontal Field of View (angle) where the distance measurement is valid. NaN if unknown.
	HorizontalFov float32
	// Vertical Field of View (angle) where the distance measurement is valid. NaN if unknown.
	VerticalFov float32
	// Quaternion of the sensor orientation in vehicle body frame (w, x, y, z order, zero-rotation is 1, 0, 0, 0). Zero-rotation is along the vehicle body x-axis. This field is required if orientation is set to MAV_SENSOR_ROTATION_CUSTOM. Set it to 0 if invalid.
	Quaternion [4]float32 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageDistanceSensorInfo) GetID() uint32 {
	return 516
}
