//autogenerated:yes
//nolint:revive,govet,errcheck
package uavionix

import (
	"testing"
)

func TestEnum_UAVIONIX_ADSB_EMERGENCY_STATUS(t *testing.T) {
	var e UAVIONIX_ADSB_EMERGENCY_STATUS
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
