//autogenerated:yes
//nolint:revive,govet,errcheck
package uavionix_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/uavionix"
)

func TestEnum_UAVIONIX_ADSB_OUT_STATUS_FAULT(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.UAVIONIX_ADSB_OUT_STATUS_FAULT
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.UAVIONIX_ADSB_OUT_STATUS_FAULT_STATUS_MESSAGE_UNAVAIL.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.UAVIONIX_ADSB_OUT_STATUS_FAULT
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.UAVIONIX_ADSB_OUT_STATUS_FAULT_STATUS_MESSAGE_UNAVAIL, dec)
	})
}
