//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package uavionix

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// RC type
type RC_TYPE = common.RC_TYPE

const (
	// Spektrum DSM2
	RC_TYPE_SPEKTRUM_DSM2 RC_TYPE = common.RC_TYPE_SPEKTRUM_DSM2
	// Spektrum DSMX
	RC_TYPE_SPEKTRUM_DSMX RC_TYPE = common.RC_TYPE_SPEKTRUM_DSMX
)
