//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Cumulative distance traveled for each reported wheel.
type MessageWheelDistance = common.MessageWheelDistance
