//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Optical flow from an angular rate flow sensor (e.g. PX4FLOW or mouse sensor)
type MessageOpticalFlowRad = common.MessageOpticalFlowRad
