//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Reports results of completed compass calibration. Sent until MAG_CAL_ACK received.
type MessageMagCalReport = common.MessageMagCalReport
