//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

// Flight Identification for ADSB-Out vehicles.
type MessageUavionixAdsbOutCfgFlightid struct {
	// Flight Identification: 8 ASCII characters, '0' through '9', 'A' through 'Z' or space. Spaces (0x20) used as a trailing pad character, or when call sign is unavailable. Reflects Control message setting. This is null-terminated.
	FlightId string `mavlen:"9"`
}

// GetID implements the message.Message interface.
func (*MessageUavionixAdsbOutCfgFlightid) GetID() uint32 {
	return 10005
}
