//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// RTCM message for injecting into the onboard GPS (used for DGPS)
type MessageGpsRtcmData = common.MessageGpsRtcmData
