//autogenerated:yes
//nolint:revive,misspell,govet,lll
package uavionix

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Vibration levels and accelerometer clipping
type MessageVibration = common.MessageVibration
