//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package avssuas

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/standard"
)

// Enum used to indicate true or false (also: success or failure, enabled or disabled, active or inactive).
type BOOL = standard.BOOL

const (
	// False.
	BOOL_FALSE BOOL = standard.BOOL_FALSE
	// True.
	BOOL_TRUE BOOL = standard.BOOL_TRUE
)
