//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// The pressure readings for the typical setup of one absolute and differential pressure sensor. The units are as specified in each field.
type MessageScaledPressure = common.MessageScaledPressure
