//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Response to a REQUEST_EVENT in case of an error (e.g. the event is not available anymore).
type MessageResponseEventError = common.MessageResponseEventError
