//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Reports results of completed compass calibration. Sent until MAG_CAL_ACK received.
type MessageMagCalReport = common.MessageMagCalReport
