//autogenerated:yes
//nolint:revive,misspell,govet,lll
package avssuas

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Setup a MAVLink2 signing key. If called with secret_key of all zero and zero initial_timestamp will disable signing
type MessageSetupSigning = common.MessageSetupSigning
