//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Status of simulation environment, if used
type MessageSimState = common.MessageSimState
