//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Camera-IMU triggering and synchronisation message.
type MessageCameraTrigger = common.MessageCameraTrigger
