//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Message appropriate for high latency connections like Iridium (version 2)
type MessageHighLatency2 = common.MessageHighLatency2
