//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Reply to LOG_REQUEST_LIST
type MessageLogEntry = common.MessageLogEntry
