//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Hardware status sent by an onboard computer.
type MessageOnboardComputerStatus = common.MessageOnboardComputerStatus
