//autogenerated:yes
//nolint:revive,misspell,govet,lll
package stemstudios

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Reply to LOG_REQUEST_DATA
type MessageLogData = common.MessageLogData
