//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Motion capture attitude and position
type MessageAttPosMocap = common.MessageAttPosMocap
