//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Reply to LOG_REQUEST_LIST
type MessageLogEntry = common.MessageLogEntry
