//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Bind a RC channel to a parameter. The parameter should change according to the RC channel value.
type MessageParamMapRc = common.MessageParamMapRc
