//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Status of the Iridium SBD link.
type MessageIsbdLinkStatus = common.MessageIsbdLinkStatus
