//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Power supply status
type MessagePowerStatus = common.MessagePowerStatus
