//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Sent from autopilot to simulation. Hardware in the loop control outputs (replacement for HIL_CONTROLS)
type MessageHilActuatorControls = common.MessageHilActuatorControls
