//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Request a chunk of a log
type MessageLogRequestData = common.MessageLogRequestData
