//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Erase all logs
type MessageLogErase = common.MessageLogErase
