//autogenerated:yes
//nolint:revive,misspell,govet,lll
package paparazzi

// Request the overall list of mission items from the system/component.
type MessageScriptRequestList struct {
	// System ID
	TargetSystem uint8
	// Component ID
	TargetComponent uint8
}

// GetID implements the message.Message interface.
func (*MessageScriptRequestList) GetID() uint32 {
	return 182
}
