//autogenerated:yes
//nolint:revive,govet,errcheck
package ardupilotmega

import (
	"testing"
)

func TestEnum_CAMERA_STATUS_TYPES(t *testing.T) {
	var e CAMERA_STATUS_TYPES
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
