//autogenerated:yes
//nolint:revive,govet,errcheck
package ardupilotmega_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/ardupilotmega"
)

func TestEnum_DEEPSTALL_STAGE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.DEEPSTALL_STAGE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.DEEPSTALL_STAGE_FLY_TO_LANDING.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.DEEPSTALL_STAGE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.DEEPSTALL_STAGE_FLY_TO_LANDING, dec)
	})
}
