//autogenerated:yes
//nolint:revive,govet,errcheck
package ardupilotmega

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_GIMBAL_AXIS_CALIBRATION_STATUS(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e GIMBAL_AXIS_CALIBRATION_STATUS
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := GIMBAL_AXIS_CALIBRATION_STATUS_IN_PROGRESS.MarshalText()
		require.NoError(t, err)

		var dec GIMBAL_AXIS_CALIBRATION_STATUS
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, GIMBAL_AXIS_CALIBRATION_STATUS_IN_PROGRESS, dec)
	})
}
