//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package ardupilotmega

import (
	"fmt"
	"strings"
)

type GOPRO_FRAME_RATE uint32

const (
	// 12 FPS.
	GOPRO_FRAME_RATE_12 GOPRO_FRAME_RATE = 0
	// 15 FPS.
	GOPRO_FRAME_RATE_15 GOPRO_FRAME_RATE = 1
	// 24 FPS.
	GOPRO_FRAME_RATE_24 GOPRO_FRAME_RATE = 2
	// 25 FPS.
	GOPRO_FRAME_RATE_25 GOPRO_FRAME_RATE = 3
	// 30 FPS.
	GOPRO_FRAME_RATE_30 GOPRO_FRAME_RATE = 4
	// 48 FPS.
	GOPRO_FRAME_RATE_48 GOPRO_FRAME_RATE = 5
	// 50 FPS.
	GOPRO_FRAME_RATE_50 GOPRO_FRAME_RATE = 6
	// 60 FPS.
	GOPRO_FRAME_RATE_60 GOPRO_FRAME_RATE = 7
	// 80 FPS.
	GOPRO_FRAME_RATE_80 GOPRO_FRAME_RATE = 8
	// 90 FPS.
	GOPRO_FRAME_RATE_90 GOPRO_FRAME_RATE = 9
	// 100 FPS.
	GOPRO_FRAME_RATE_100 GOPRO_FRAME_RATE = 10
	// 120 FPS.
	GOPRO_FRAME_RATE_120 GOPRO_FRAME_RATE = 11
	// 240 FPS.
	GOPRO_FRAME_RATE_240 GOPRO_FRAME_RATE = 12
	// 12.5 FPS.
	GOPRO_FRAME_RATE_12_5 GOPRO_FRAME_RATE = 13
)

var labels_GOPRO_FRAME_RATE = map[GOPRO_FRAME_RATE]string{
	GOPRO_FRAME_RATE_12:   "GOPRO_FRAME_RATE_12",
	GOPRO_FRAME_RATE_15:   "GOPRO_FRAME_RATE_15",
	GOPRO_FRAME_RATE_24:   "GOPRO_FRAME_RATE_24",
	GOPRO_FRAME_RATE_25:   "GOPRO_FRAME_RATE_25",
	GOPRO_FRAME_RATE_30:   "GOPRO_FRAME_RATE_30",
	GOPRO_FRAME_RATE_48:   "GOPRO_FRAME_RATE_48",
	GOPRO_FRAME_RATE_50:   "GOPRO_FRAME_RATE_50",
	GOPRO_FRAME_RATE_60:   "GOPRO_FRAME_RATE_60",
	GOPRO_FRAME_RATE_80:   "GOPRO_FRAME_RATE_80",
	GOPRO_FRAME_RATE_90:   "GOPRO_FRAME_RATE_90",
	GOPRO_FRAME_RATE_100:  "GOPRO_FRAME_RATE_100",
	GOPRO_FRAME_RATE_120:  "GOPRO_FRAME_RATE_120",
	GOPRO_FRAME_RATE_240:  "GOPRO_FRAME_RATE_240",
	GOPRO_FRAME_RATE_12_5: "GOPRO_FRAME_RATE_12_5",
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e GOPRO_FRAME_RATE) MarshalText() ([]byte, error) {
	var names []string
	for mask, label := range labels_GOPRO_FRAME_RATE {
		if e&mask == mask {
			names = append(names, label)
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *GOPRO_FRAME_RATE) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask GOPRO_FRAME_RATE
	for _, label := range labels {
		found := false
		for value, l := range labels_GOPRO_FRAME_RATE {
			if l == label {
				mask |= value
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e GOPRO_FRAME_RATE) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
