//autogenerated:yes
//nolint:revive,govet,errcheck
package ardupilotmega

import (
	"testing"
)

func TestEnum_MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL(t *testing.T) {
	var e MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
