//autogenerated:yes
//nolint:revive,govet,errcheck
package ardupilotmega

import (
	"testing"
)

func TestEnum_GOPRO_CAPTURE_MODE(t *testing.T) {
	var e GOPRO_CAPTURE_MODE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
