//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package ardupilotmega

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/icarous"
)

type ICAROUS_TRACK_BAND_TYPES = icarous.ICAROUS_TRACK_BAND_TYPES

const (
	ICAROUS_TRACK_BAND_TYPE_NONE     ICAROUS_TRACK_BAND_TYPES = icarous.ICAROUS_TRACK_BAND_TYPE_NONE
	ICAROUS_TRACK_BAND_TYPE_NEAR     ICAROUS_TRACK_BAND_TYPES = icarous.ICAROUS_TRACK_BAND_TYPE_NEAR
	ICAROUS_TRACK_BAND_TYPE_RECOVERY ICAROUS_TRACK_BAND_TYPES = icarous.ICAROUS_TRACK_BAND_TYPE_RECOVERY
)
