//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package ardupilotmega

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

type MAV_ODID_CLASSIFICATION_TYPE = common.MAV_ODID_CLASSIFICATION_TYPE

const (
	// The classification type for the UA is undeclared.
	MAV_ODID_CLASSIFICATION_TYPE_UNDECLARED MAV_ODID_CLASSIFICATION_TYPE = common.MAV_ODID_CLASSIFICATION_TYPE_UNDECLARED
	// The classification type for the UA follows EU (European Union) specifications.
	MAV_ODID_CLASSIFICATION_TYPE_EU MAV_ODID_CLASSIFICATION_TYPE = common.MAV_ODID_CLASSIFICATION_TYPE_EU
)
