//autogenerated:yes
//nolint:revive,govet,errcheck
package ardupilotmega_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/ardupilotmega"
)

func TestEnum_GOPRO_FIELD_OF_VIEW(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.GOPRO_FIELD_OF_VIEW
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.GOPRO_FIELD_OF_VIEW_WIDE.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.GOPRO_FIELD_OF_VIEW
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.GOPRO_FIELD_OF_VIEW_WIDE, dec)
	})
}
