//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package ardupilotmega

import (
	"fmt"
	"strings"
)

type MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL uint32

const (
	// Switch Low.
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_LOW MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL = 0
	// Switch Middle.
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_MIDDLE MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL = 1
	// Switch High.
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_HIGH MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL = 2
)

var labels_MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL = map[MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL]string{
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_LOW:    "MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_LOW",
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_MIDDLE: "MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_MIDDLE",
	MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_HIGH:   "MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL_HIGH",
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL) MarshalText() ([]byte, error) {
	var names []string
	for mask, label := range labels_MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL {
		if e&mask == mask {
			names = append(names, label)
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL
	for _, label := range labels {
		found := false
		for value, l := range labels_MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL {
			if l == label {
				mask |= value
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e MAV_CMD_DO_AUX_FUNCTION_SWITCH_LEVEL) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
