//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Metrics typically displayed on a HUD for fixed wing aircraft.
type MessageVfrHud = common.MessageVfrHud
