//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/cubepilot"
)

// Information about video stream
type MessageHerelinkVideoStreamInformation = cubepilot.MessageHerelinkVideoStreamInformation
