//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/cubepilot"
)

// Start firmware update with encapsulated data.
type MessageCubepilotFirmwareUpdateStart = cubepilot.MessageCubepilotFirmwareUpdateStart
