//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// An ack for a LOGGING_DATA_ACKED message
type MessageLoggingAck = common.MessageLoggingAck
