//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Response from a PARAM_EXT_SET message.
type MessageParamExtAck = common.MessageParamExtAck
