//autogenerated:yes
//nolint:revive,misspell,govet,lll
package ardupilotmega

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Delete all mission items at once.
type MessageMissionClearAll = common.MessageMissionClearAll
