//autogenerated:yes
//nolint:golint,misspell,govet,lll
package ardupilotmega

// Message with some status from APM to GCS about camera or antenna mount.
type MessageMountStatus struct {
	// System ID.
	TargetSystem uint8
	// Component ID.
	TargetComponent uint8
	// Pitch.
	PointingA int32
	// Roll.
	PointingB int32
	// Yaw.
	PointingC int32
}

// GetID implements the msg.Message interface.
func (*MessageMountStatus) GetID() uint32 {
	return 158
}
