//autogenerated:yes
//nolint:revive,govet,errcheck
package marsh

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_MARSH_TYPE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e MARSH_TYPE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := MARSH_TYPE_MANAGER.MarshalText()
		require.NoError(t, err)

		var dec MARSH_TYPE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, MARSH_TYPE_MANAGER, dec)
	})
}
