//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package marsh

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Navigational status of AIS vessel, enum duplicated from AIS standard, https://gpsd.gitlab.io/gpsd/AIVDM.html
type AIS_NAV_STATUS = common.AIS_NAV_STATUS

const (
	// Under way using engine.
	AIS_NAV_STATUS_UNDER_WAY                   AIS_NAV_STATUS = common.AIS_NAV_STATUS_UNDER_WAY
	AIS_NAV_STATUS_ANCHORED                    AIS_NAV_STATUS = common.AIS_NAV_STATUS_ANCHORED
	AIS_NAV_STATUS_UN_COMMANDED                AIS_NAV_STATUS = common.AIS_NAV_STATUS_UN_COMMANDED
	AIS_NAV_STATUS_RESTRICTED_MANOEUVERABILITY AIS_NAV_STATUS = common.AIS_NAV_STATUS_RESTRICTED_MANOEUVERABILITY
	AIS_NAV_STATUS_DRAUGHT_CONSTRAINED         AIS_NAV_STATUS = common.AIS_NAV_STATUS_DRAUGHT_CONSTRAINED
	AIS_NAV_STATUS_MOORED                      AIS_NAV_STATUS = common.AIS_NAV_STATUS_MOORED
	AIS_NAV_STATUS_AGROUND                     AIS_NAV_STATUS = common.AIS_NAV_STATUS_AGROUND
	AIS_NAV_STATUS_FISHING                     AIS_NAV_STATUS = common.AIS_NAV_STATUS_FISHING
	AIS_NAV_STATUS_SAILING                     AIS_NAV_STATUS = common.AIS_NAV_STATUS_SAILING
	AIS_NAV_STATUS_RESERVED_HSC                AIS_NAV_STATUS = common.AIS_NAV_STATUS_RESERVED_HSC
	AIS_NAV_STATUS_RESERVED_WIG                AIS_NAV_STATUS = common.AIS_NAV_STATUS_RESERVED_WIG
	AIS_NAV_STATUS_RESERVED_1                  AIS_NAV_STATUS = common.AIS_NAV_STATUS_RESERVED_1
	AIS_NAV_STATUS_RESERVED_2                  AIS_NAV_STATUS = common.AIS_NAV_STATUS_RESERVED_2
	AIS_NAV_STATUS_RESERVED_3                  AIS_NAV_STATUS = common.AIS_NAV_STATUS_RESERVED_3
	// Search And Rescue Transponder.
	AIS_NAV_STATUS_AIS_SART AIS_NAV_STATUS = common.AIS_NAV_STATUS_AIS_SART
	// Not available (default).
	AIS_NAV_STATUS_UNKNOWN AIS_NAV_STATUS = common.AIS_NAV_STATUS_UNKNOWN
)
