//autogenerated:yes
//nolint:revive,govet,errcheck
package marsh_test

import (
	"testing"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/marsh"
	"github.com/stretchr/testify/require"
)

func TestEnum_CONTROL_AXIS(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.CONTROL_AXIS
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.CONTROL_AXIS_ROLL.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.CONTROL_AXIS
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.CONTROL_AXIS_ROLL, dec)
	})
}
