//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Barometer readings for 2nd barometer
type MessageScaledPressure2 = common.MessageScaledPressure2
