//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// EFI status output
type MessageEfiStatus = common.MessageEfiStatus
