//autogenerated:yes
//nolint:revive,misspell,govet,lll
package marsh

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Motion capture attitude and position
type MessageAttPosMocap = common.MessageAttPosMocap
