//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_MAV_GENERATOR_STATUS_FLAG(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e MAV_GENERATOR_STATUS_FLAG
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := MAV_GENERATOR_STATUS_FLAG_OFF.MarshalText()
		require.NoError(t, err)

		var dec MAV_GENERATOR_STATUS_FLAG
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, MAV_GENERATOR_STATUS_FLAG_OFF, dec)
	})
}
