//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_VIDEO_STREAM_STATUS_FLAGS(t *testing.T) {
	var e VIDEO_STREAM_STATUS_FLAGS
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
