//autogenerated:yes
//nolint:revive,govet,errcheck
package common_test

import (
	"testing"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
	"github.com/stretchr/testify/require"
)

func TestEnum_ADSB_ALTITUDE_TYPE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.ADSB_ALTITUDE_TYPE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.ADSB_ALTITUDE_TYPE_PRESSURE_QNH.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.ADSB_ALTITUDE_TYPE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.ADSB_ALTITUDE_TYPE_PRESSURE_QNH, dec)
	})
}
