//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_PARACHUTE_ACTION(t *testing.T) {
	var e PARACHUTE_ACTION
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
