//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_STORAGE_USAGE_FLAG(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e STORAGE_USAGE_FLAG
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := STORAGE_USAGE_FLAG_SET.MarshalText()
		require.NoError(t, err)

		var dec STORAGE_USAGE_FLAG
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, STORAGE_USAGE_FLAG_SET, dec)
	})
}
