//autogenerated:yes
//nolint:revive,govet,errcheck
package common_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

func TestEnum_MAV_LANDED_STATE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.MAV_LANDED_STATE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.MAV_LANDED_STATE_UNDEFINED.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.MAV_LANDED_STATE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.MAV_LANDED_STATE_UNDEFINED, dec)
	})
}
