//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package common

import (
	"fmt"
	"strconv"
	"strings"
)

// Engine control options
type ENGINE_CONTROL_OPTIONS uint64

const (
	// Allow starting the engine while disarmed (without changing the vehicle's armed state). This effectively arms just the ICE, without arming the vehicle to start other motors or propellers.
	ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED ENGINE_CONTROL_OPTIONS = 1
)

var values_ENGINE_CONTROL_OPTIONS = []ENGINE_CONTROL_OPTIONS{
	ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED,
}

var value_to_label_ENGINE_CONTROL_OPTIONS = map[ENGINE_CONTROL_OPTIONS]string{
	ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED: "ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED",
}

var label_to_value_ENGINE_CONTROL_OPTIONS = map[string]ENGINE_CONTROL_OPTIONS{
	"ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED": ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e ENGINE_CONTROL_OPTIONS) MarshalText() ([]byte, error) {
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for _, val := range values_ENGINE_CONTROL_OPTIONS {
		if e&val == val {
			names = append(names, value_to_label_ENGINE_CONTROL_OPTIONS[val])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *ENGINE_CONTROL_OPTIONS) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask ENGINE_CONTROL_OPTIONS
	for _, label := range labels {
		if value, ok := label_to_value_ENGINE_CONTROL_OPTIONS[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= ENGINE_CONTROL_OPTIONS(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e ENGINE_CONTROL_OPTIONS) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
