//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_UTM_DATA_AVAIL_FLAGS(t *testing.T) {
	var e UTM_DATA_AVAIL_FLAGS
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
