//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_MAV_GOTO(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e MAV_GOTO
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := MAV_GOTO_DO_HOLD.MarshalText()
		require.NoError(t, err)

		var dec MAV_GOTO
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, MAV_GOTO_DO_HOLD, dec)
	})
}
