//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_AIS_TYPE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e AIS_TYPE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := AIS_TYPE_UNKNOWN.MarshalText()
		require.NoError(t, err)

		var dec AIS_TYPE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, AIS_TYPE_UNKNOWN, dec)
	})
}
