//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_SAFETY_SWITCH_STATE(t *testing.T) {
	var e SAFETY_SWITCH_STATE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
