//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_GPS_FIX_TYPE(t *testing.T) {
	var e GPS_FIX_TYPE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
