//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_ODID_ID_TYPE(t *testing.T) {
	var e MAV_ODID_ID_TYPE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
