//autogenerated:yes
//nolint:revive,govet,errcheck
package common_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

func TestEnum_FAILURE_UNIT(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.FAILURE_UNIT
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.FAILURE_UNIT_SENSOR_GYRO.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.FAILURE_UNIT
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.FAILURE_UNIT_SENSOR_GYRO, dec)
	})
}
