//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package common

import (
	"fmt"
	"strconv"
)

// Enumeration of battery types
type MAV_BATTERY_TYPE uint32

const (
	// Not specified.
	MAV_BATTERY_TYPE_UNKNOWN MAV_BATTERY_TYPE = 0
	// Lithium polymer battery
	MAV_BATTERY_TYPE_LIPO MAV_BATTERY_TYPE = 1
	// Lithium-iron-phosphate battery
	MAV_BATTERY_TYPE_LIFE MAV_BATTERY_TYPE = 2
	// Lithium-ION battery
	MAV_BATTERY_TYPE_LION MAV_BATTERY_TYPE = 3
	// Nickel metal hydride battery
	MAV_BATTERY_TYPE_NIMH MAV_BATTERY_TYPE = 4
)

var labels_MAV_BATTERY_TYPE = map[MAV_BATTERY_TYPE]string{
	MAV_BATTERY_TYPE_UNKNOWN: "MAV_BATTERY_TYPE_UNKNOWN",
	MAV_BATTERY_TYPE_LIPO:    "MAV_BATTERY_TYPE_LIPO",
	MAV_BATTERY_TYPE_LIFE:    "MAV_BATTERY_TYPE_LIFE",
	MAV_BATTERY_TYPE_LION:    "MAV_BATTERY_TYPE_LION",
	MAV_BATTERY_TYPE_NIMH:    "MAV_BATTERY_TYPE_NIMH",
}

var values_MAV_BATTERY_TYPE = map[string]MAV_BATTERY_TYPE{
	"MAV_BATTERY_TYPE_UNKNOWN": MAV_BATTERY_TYPE_UNKNOWN,
	"MAV_BATTERY_TYPE_LIPO":    MAV_BATTERY_TYPE_LIPO,
	"MAV_BATTERY_TYPE_LIFE":    MAV_BATTERY_TYPE_LIFE,
	"MAV_BATTERY_TYPE_LION":    MAV_BATTERY_TYPE_LION,
	"MAV_BATTERY_TYPE_NIMH":    MAV_BATTERY_TYPE_NIMH,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e MAV_BATTERY_TYPE) MarshalText() ([]byte, error) {
	name, ok := labels_MAV_BATTERY_TYPE[e]
	if !ok {
		return nil, fmt.Errorf("invalid value %d", e)
	}
	return []byte(name), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *MAV_BATTERY_TYPE) UnmarshalText(text []byte) error {
	value, ok := values_MAV_BATTERY_TYPE[string(text)]
	if !ok {
		return fmt.Errorf("invalid label '%s'", text)
	}
	*e = value
	return nil
}

// String implements the fmt.Stringer interface.
func (e MAV_BATTERY_TYPE) String() string {
	name, ok := labels_MAV_BATTERY_TYPE[e]
	if !ok {
		return strconv.Itoa(int(e))
	}
	return name
}
