//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_FTP_OPCODE(t *testing.T) {
	var e MAV_FTP_OPCODE
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
