//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_EVENT_ERROR_REASON(t *testing.T) {
	var e MAV_EVENT_ERROR_REASON
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
