//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_GPS_INPUT_IGNORE_FLAGS(t *testing.T) {
	var e GPS_INPUT_IGNORE_FLAGS
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
