//autogenerated:yes
//nolint:revive,govet,errcheck
package common_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

func TestEnum_FOLLOW_TARGET_CAP_FLAGS(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.FOLLOW_TARGET_CAP_FLAGS
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.FOLLOW_TARGET_CAP_FLAGS_POS.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.FOLLOW_TARGET_CAP_FLAGS
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.FOLLOW_TARGET_CAP_FLAGS_POS, dec)
	})
}
