//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package common

import (
	"fmt"
	"strconv"
)

// Actions being taken to mitigate/prevent fence breach
type FENCE_MITIGATE uint32

const (
	// Unknown
	FENCE_MITIGATE_UNKNOWN FENCE_MITIGATE = 0
	// No actions being taken
	FENCE_MITIGATE_NONE FENCE_MITIGATE = 1
	// Velocity limiting active to prevent breach
	FENCE_MITIGATE_VEL_LIMIT FENCE_MITIGATE = 2
)

var labels_FENCE_MITIGATE = map[FENCE_MITIGATE]string{
	FENCE_MITIGATE_UNKNOWN:   "FENCE_MITIGATE_UNKNOWN",
	FENCE_MITIGATE_NONE:      "FENCE_MITIGATE_NONE",
	FENCE_MITIGATE_VEL_LIMIT: "FENCE_MITIGATE_VEL_LIMIT",
}

var values_FENCE_MITIGATE = map[string]FENCE_MITIGATE{
	"FENCE_MITIGATE_UNKNOWN":   FENCE_MITIGATE_UNKNOWN,
	"FENCE_MITIGATE_NONE":      FENCE_MITIGATE_NONE,
	"FENCE_MITIGATE_VEL_LIMIT": FENCE_MITIGATE_VEL_LIMIT,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e FENCE_MITIGATE) MarshalText() ([]byte, error) {
	name, ok := labels_FENCE_MITIGATE[e]
	if !ok {
		return nil, fmt.Errorf("invalid value %d", e)
	}
	return []byte(name), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *FENCE_MITIGATE) UnmarshalText(text []byte) error {
	value, ok := values_FENCE_MITIGATE[string(text)]
	if !ok {
		return fmt.Errorf("invalid label '%s'", text)
	}
	*e = value
	return nil
}

// String implements the fmt.Stringer interface.
func (e FENCE_MITIGATE) String() string {
	name, ok := labels_FENCE_MITIGATE[e]
	if !ok {
		return strconv.Itoa(int(e))
	}
	return name
}
