//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_PREFLIGHT_STORAGE_PARAMETER_ACTION(t *testing.T) {
	var e PREFLIGHT_STORAGE_PARAMETER_ACTION
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
