//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"
)

func TestEnum_MAV_DATA_STREAM(t *testing.T) {
	var e MAV_DATA_STREAM
	e.UnmarshalText([]byte{})
	e.MarshalText()
	e.String()
}
