//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_MAV_FTP_ERR(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e MAV_FTP_ERR
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := MAV_FTP_ERR_NONE.MarshalText()
		require.NoError(t, err)

		var dec MAV_FTP_ERR
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, MAV_FTP_ERR_NONE, dec)
	})
}
