//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_WINCH_ACTIONS(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e WINCH_ACTIONS
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := WINCH_RELAXED.MarshalText()
		require.NoError(t, err)

		var dec WINCH_ACTIONS
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, WINCH_RELAXED, dec)
	})
}
