//autogenerated:yes
//nolint:revive,misspell,govet,lll
package common

// The system time is the time of the sender's master clock.
// This can be emitted by flight controllers, onboard computers, or other components in the MAVLink network.
// Components that are using a less reliable time source, such as a battery-backed real time clock, can choose to match their system clock to that of a system that indicates a more recent time.
// This allows more broadly accurate date stamping of logs, and so on.
// If precise time synchronization is needed then use TIMESYNC instead.
type MessageSystemTime struct {
	// Timestamp (UNIX epoch time).
	TimeUnixUsec uint64
	// Timestamp (time since system boot).
	TimeBootMs uint32
}

// GetID implements the message.Message interface.
func (*MessageSystemTime) GetID() uint32 {
	return 2
}
