//autogenerated:yes
//nolint:revive,misspell,govet,lll
package common

// Delete all mission items at once.
type MessageMissionClearAll struct {
	// System ID
	TargetSystem uint8
	// Component ID
	TargetComponent uint8
	// Mission type.
	MissionType MAV_MISSION_TYPE `mavenum:"uint8" mavext:"true"`
}

// GetID implements the msg.Message interface.
func (*MessageMissionClearAll) GetID() uint32 {
	return 45
}
