//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/development"
)

// RADIO_RC_CHANNELS flags (bitmask).
type RADIO_RC_CHANNELS_FLAGS = development.RADIO_RC_CHANNELS_FLAGS

const (
	// Failsafe is active. The content of the RC channels data in the RADIO_RC_CHANNELS message is implementation dependent.
	RADIO_RC_CHANNELS_FLAGS_FAILSAFE RADIO_RC_CHANNELS_FLAGS = development.RADIO_RC_CHANNELS_FLAGS_FAILSAFE
	// Channel data may be out of date. This is set when the receiver is unable to validate incoming data from the transmitter and has therefore resent the last valid data it received.
	RADIO_RC_CHANNELS_FLAGS_OUTDATED RADIO_RC_CHANNELS_FLAGS = development.RADIO_RC_CHANNELS_FLAGS_OUTDATED
)
