//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/stemstudios"
)

// How to configure LEDs. We can:
// - Set all LEDs to the first color in our colors array.
// - Set up to 8 consecutive LEDs, starting from a given index, to colors provided in an array.
// - Set the LED colors to change according to the flight mode.
// - Turn all LEDs off (clear).
type LED_CONFIG_MODE = stemstudios.LED_CONFIG_MODE

const (
	// Set all LEDs in the target strip to the first color in our colors array.
	LED_CONFIG_MODE_ALL LED_CONFIG_MODE = stemstudios.LED_CONFIG_MODE_ALL
	// Set up to 8 consecutive LEDs, starting from the given index, to the colors provided in the colors array.
	LED_CONFIG_MODE_INDEX LED_CONFIG_MODE = stemstudios.LED_CONFIG_MODE_INDEX
	// Set all LEDs in target strip to change color according to the flight mode.
	LED_CONFIG_MODE_FOLLOW_FLIGHT_MODE LED_CONFIG_MODE = stemstudios.LED_CONFIG_MODE_FOLLOW_FLIGHT_MODE
	// Set all LEDs in the target strip to black (turn off).
	LED_CONFIG_MODE_CLEAR LED_CONFIG_MODE = stemstudios.LED_CONFIG_MODE_CLEAR
)
