//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/asluav"
)

type GSM_LINK_TYPE = asluav.GSM_LINK_TYPE

const (
	// no service
	GSM_LINK_TYPE_NONE GSM_LINK_TYPE = asluav.GSM_LINK_TYPE_NONE
	// link type unknown
	GSM_LINK_TYPE_UNKNOWN GSM_LINK_TYPE = asluav.GSM_LINK_TYPE_UNKNOWN
	// 2G (GSM/GRPS/EDGE) link
	GSM_LINK_TYPE_2G GSM_LINK_TYPE = asluav.GSM_LINK_TYPE_2G
	// 3G link (WCDMA/HSDPA/HSPA)
	GSM_LINK_TYPE_3G GSM_LINK_TYPE = asluav.GSM_LINK_TYPE_3G
	// 4G link (LTE)
	GSM_LINK_TYPE_4G GSM_LINK_TYPE = asluav.GSM_LINK_TYPE_4G
)
