//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// A mapping of rover flight modes for custom_mode field of heartbeat.
type ROVER_MODE = ardupilotmega.ROVER_MODE

const (
	// MANUAL
	ROVER_MODE_MANUAL ROVER_MODE = ardupilotmega.ROVER_MODE_MANUAL
	// ACRO
	ROVER_MODE_ACRO ROVER_MODE = ardupilotmega.ROVER_MODE_ACRO
	// STEERING
	ROVER_MODE_STEERING ROVER_MODE = ardupilotmega.ROVER_MODE_STEERING
	// HOLD
	ROVER_MODE_HOLD ROVER_MODE = ardupilotmega.ROVER_MODE_HOLD
	// LOITER
	ROVER_MODE_LOITER ROVER_MODE = ardupilotmega.ROVER_MODE_LOITER
	// FOLLOW
	ROVER_MODE_FOLLOW ROVER_MODE = ardupilotmega.ROVER_MODE_FOLLOW
	// SIMPLE
	ROVER_MODE_SIMPLE ROVER_MODE = ardupilotmega.ROVER_MODE_SIMPLE
	// DOCK
	ROVER_MODE_DOCK ROVER_MODE = ardupilotmega.ROVER_MODE_DOCK
	// CIRCLE
	ROVER_MODE_CIRCLE ROVER_MODE = ardupilotmega.ROVER_MODE_CIRCLE
	// AUTO
	ROVER_MODE_AUTO ROVER_MODE = ardupilotmega.ROVER_MODE_AUTO
	// RTL
	ROVER_MODE_RTL ROVER_MODE = ardupilotmega.ROVER_MODE_RTL
	// SMART RTL
	ROVER_MODE_SMART_RTL ROVER_MODE = ardupilotmega.ROVER_MODE_SMART_RTL
	// GUIDED
	ROVER_MODE_GUIDED ROVER_MODE = ardupilotmega.ROVER_MODE_GUIDED
	// INITIALISING
	ROVER_MODE_INITIALIZING ROVER_MODE = ardupilotmega.ROVER_MODE_INITIALIZING
)
