//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package all

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/uavionix"
)

// GPS longitudinal offset encoding
type UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON = uavionix.UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON

const (
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON_NO_DATA           UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON = uavionix.UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON_NO_DATA
	UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON_APPLIED_BY_SENSOR UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON = uavionix.UAVIONIX_ADSB_OUT_CFG_GPS_OFFSET_LON_APPLIED_BY_SENSOR
)
