//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Distance sensor information for an onboard rangefinder.
type MessageDistanceSensor = common.MessageDistanceSensor
