//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// Request to set a GOPRO_COMMAND with a desired.
type MessageGoproSetRequest = ardupilotmega.MessageGoproSetRequest
