//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/csairlink"
)

// Response information about the connected device
type MessageAirlinkEyeGsHolePushResponse = csairlink.MessageAirlinkEyeGsHolePushResponse
