//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// Water depth
type MessageWaterDepth = ardupilotmega.MessageWaterDepth
