//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/ualberta"
)

// Complete set of calibration parameters for the radio
type MessageRadioCalibration = ualberta.MessageRadioCalibration
