//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Control message for rate gimbal.
type MessageGimbalControl = ardupilotmega.MessageGimbalControl
