//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// Control on-board Camera Control System to take shots.
type MessageDigicamControl = ardupilotmega.MessageDigicamControl
