//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/csairlink"
)

// Authorization package
type MessageAirlinkAuth = csairlink.MessageAirlinkAuth
