//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/asluav"
)

// ASL-fixed-wing controller data
type MessageAslctrlData = asluav.MessageAslctrlData
