//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// ESC Telemetry Data for ESCs 1 to 4, matching data sent by BLHeli ESCs.
type MessageEscTelemetry_1To_4 = ardupilotmega.MessageEscTelemetry_1To_4
