//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/pythonarraytest"
)

// Array test #0.
type MessageArrayTest_0 = pythonarraytest.MessageArrayTest_0
