//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/development"
)

// Highly bandwidth-efficient RC override message for professional networked operations (LTE, Zigbee, GCP).
// Supersedes RC_CHANNELS_OVERRIDE by adding 32-channel support and a bitmask for multi-master conflict avoidance.
// Uses centered-at-zero values and extension-field placement to maximize MAVLink 2 trailing-zero truncation.
type MessageRcChannelsOverrideV2 = development.MessageRcChannelsOverrideV2
