//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/cubepilot"
)

// offset response to encapsulated data.
type MessageCubepilotFirmwareUpdateResp = cubepilot.MessageCubepilotFirmwareUpdateResp
