//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/ualberta"
)

// Accelerometer and Gyro biases from the navigation filter
type MessageNavFilterBias = ualberta.MessageNavFilterBias
