//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/development"
)

// Response from a PARAM_SET message when it is used in a transaction.
type MessageParamAckTransaction = development.MessageParamAckTransaction
