//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// Status of key hardware.
type MessageHwstatus = ardupilotmega.MessageHwstatus
