//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Angle of Attack and Side Slip Angle.
type MessageAoaSsa = ardupilotmega.MessageAoaSsa
