//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/pythonarraytest"
)

// Array test #5.
type MessageArrayTest_5 = pythonarraytest.MessageArrayTest_5
