//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/pythonarraytest"
)

// Array test #1.
type MessageArrayTest_1 = pythonarraytest.MessageArrayTest_1
