//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/asluav"
)

// ASL-fixed-wing controller debug data
type MessageAslctrlDebug = asluav.MessageAslctrlDebug
