//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ualberta"
)

// System status specific to ualberta uav
type MessageUalbertaSysStatus = ualberta.MessageUalbertaSysStatus
