//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Local position/attitude estimate from a vision source.
type MessageVisionPositionEstimate = common.MessageVisionPositionEstimate
