//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/pythonarraytest"
)

// Array test #3.
type MessageArrayTest_3 = pythonarraytest.MessageArrayTest_3
