//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Set the vehicle attitude and body angular rates.
type MessageSetActuatorControlTarget = common.MessageSetActuatorControlTarget
