//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Reports progress of compass calibration.
type MessageMagCalProgress = ardupilotmega.MessageMagCalProgress
