//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/avssuas"
)

// Drone operation mode.
type MessageAvssDroneOperationMode = avssuas.MessageAvssDroneOperationMode
