//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Sent from autopilot to simulation. Hardware in the loop control outputs
type MessageHilControls = common.MessageHilControls
