//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// A rally point. Used to set a point when from GCS -> MAV. Also used to return a point from MAV -> GCS.
type MessageRallyPoint = ardupilotmega.MessageRallyPoint
