//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// Obstacle located as a 3D vector.
type MessageObstacleDistance_3d = ardupilotmega.MessageObstacleDistance_3d
