//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/cubepilot"
)

// offset response to encapsulated data.
type MessageCubepilotFirmwareUpdateResp = cubepilot.MessageCubepilotFirmwareUpdateResp
