//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/aler9/gomavlib/pkg/dialects/asluav"
)

// Monitoring of power board status
type MessageSensPowerBoard = asluav.MessageSensPowerBoard
