//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/storm32"
)

// Radio link information. Tx: ground-side device, Rx: vehicle-side device.
// The values of the fields in this message do normally not or only slowly change with time, and for most times the message can be send at a low rate, like 0.2 Hz.
// If values change then the message should temporarily be send more often to inform the system about the changes.
// The target_system field should normally be set to the system id of the system the link is connected to, typically the flight controller.
// The target_component field can normally be set to 0, so that all components of the system can receive the message.
type MessageMlrsRadioLinkInformation = storm32.MessageMlrsRadioLinkInformation
