//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Response from a PARAM_EXT_SET message.
type MessageParamExtAck = common.MessageParamExtAck
