//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/stemstudios"
)

// Set the colors on an LED strip. The mode field determines how the colors are set. We can:
// - Set all LEDs to the first color in our colors array.
// - Set up to 8 consecutive LEDs, starting from a given index, to colors provided in an array.
// - Set the LED colors to change according to the flight mode.
// - Turn all LEDs off (clear).
// Which LED strip to configure is specified by the id field.
// The colors field is an array of up to 8 colors, each represented as a 32-bit integer in the format 0xWWRRGGBB
// where WW is white, RR is the intensity of the red color channel, GG is green, and BB is blue.
type MessageLedStripConfig = stemstudios.MessageLedStripConfig
