//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

// Camera Event.
type MessageCameraStatus struct {
	// Image timestamp (since UNIX epoch, according to camera clock).
	TimeUsec uint64
	// System ID.
	TargetSystem uint8
	// Camera ID.
	CamIdx uint8
	// Image index.
	ImgIdx uint16
	// Event type.
	EventId CAMERA_STATUS_TYPES `mavenum:"uint8"`
	// Parameter 1 (meaning depends on event_id, see CAMERA_STATUS_TYPES enum).
	P1 float32
	// Parameter 2 (meaning depends on event_id, see CAMERA_STATUS_TYPES enum).
	P2 float32
	// Parameter 3 (meaning depends on event_id, see CAMERA_STATUS_TYPES enum).
	P3 float32
	// Parameter 4 (meaning depends on event_id, see CAMERA_STATUS_TYPES enum).
	P4 float32
}

// GetID implements the message.Message interface.
func (*MessageCameraStatus) GetID() uint32 {
	return 179
}
