//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

// Detected WiFi network status information. This message is sent per each WiFi network detected in range with known SSID and general status parameters.
type MessageWifiNetworkInfo struct {
	// Name of Wi-Fi network (SSID).
	Ssid string `mavlen:"32"`
	// WiFi network operating channel ID. Set to 0 if unknown or unidentified.
	ChannelId uint8
	// WiFi network signal quality.
	SignalQuality uint8
	// WiFi network data rate. Set to UINT16_MAX if data_rate information is not supplied.
	DataRate uint16
	// WiFi network security type.
	Security WIFI_NETWORK_SECURITY `mavenum:"uint8"`
}

// GetID implements the message.Message interface.
func (*MessageWifiNetworkInfo) GetID() uint32 {
	return 298
}
