//autogenerated:yes
//nolint:revive,misspell,govet,lll
package all

// offset response to encapsulated data.
type MessageCubepilotFirmwareUpdateResp struct {
	// System ID.
	TargetSystem uint8
	// Component ID.
	TargetComponent uint8
	// FW Offset.
	Offset uint32
}

// GetID implements the message.Message interface.
func (*MessageCubepilotFirmwareUpdateResp) GetID() uint32 {
	return 50005
}
