//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package asluav

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Status flags for GLOBAL_POSITION
type GLOBAL_POSITION_FLAGS = common.GLOBAL_POSITION_FLAGS

const (
	// Unhealthy sensor/estimator.
	GLOBAL_POSITION_UNHEALTHY GLOBAL_POSITION_FLAGS = common.GLOBAL_POSITION_UNHEALTHY
	// True if the data originates from or is consumed by the primary estimator.
	GLOBAL_POSITION_PRIMARY GLOBAL_POSITION_FLAGS = common.GLOBAL_POSITION_PRIMARY
)
