//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Power supply status
type MessagePowerStatus = common.MessagePowerStatus
