//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// RPM sensor data message.
type MessageRawRpm = common.MessageRawRpm
