//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Request to control this MAV
type MessageChangeOperatorControl = common.MessageChangeOperatorControl
