//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// The location and information of an ADSB vehicle
type MessageAdsbVehicle = common.MessageAdsbVehicle
