//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Optical flow from a flow sensor (e.g. optical mouse sensor)
type MessageOpticalFlow = common.MessageOpticalFlow
