//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Camera tracking status, sent while in active tracking. Use MAV_CMD_SET_MESSAGE_INTERVAL to define message interval.
type MessageCameraTrackingGeoStatus = common.MessageCameraTrackingGeoStatus
