//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Read out the safety zone the MAV currently assumes.
type MessageSafetyAllowedArea = common.MessageSafetyAllowedArea
