//autogenerated:yes
//nolint:revive,misspell,govet,lll
package asluav

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Accept / deny control of this MAV
type MessageChangeOperatorControlAck = common.MessageChangeOperatorControlAck
