//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package matrixpilot

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Video stream encodings
type VIDEO_STREAM_ENCODING = common.VIDEO_STREAM_ENCODING

const (
	// Stream encoding is unknown
	VIDEO_STREAM_ENCODING_UNKNOWN VIDEO_STREAM_ENCODING = common.VIDEO_STREAM_ENCODING_UNKNOWN
	// Stream encoding is H.264
	VIDEO_STREAM_ENCODING_H264 VIDEO_STREAM_ENCODING = common.VIDEO_STREAM_ENCODING_H264
	// Stream encoding is H.265
	VIDEO_STREAM_ENCODING_H265 VIDEO_STREAM_ENCODING = common.VIDEO_STREAM_ENCODING_H265
)
