//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package matrixpilot

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

type NAV_VTOL_LAND_OPTIONS = common.NAV_VTOL_LAND_OPTIONS

const (
	// Default autopilot landing behaviour.
	NAV_VTOL_LAND_OPTIONS_DEFAULT NAV_VTOL_LAND_OPTIONS = common.NAV_VTOL_LAND_OPTIONS_DEFAULT
	// Use a fixed wing spiral desent approach before landing.
	NAV_VTOL_LAND_OPTIONS_FW_SPIRAL_APPROACH NAV_VTOL_LAND_OPTIONS = common.NAV_VTOL_LAND_OPTIONS_FW_SPIRAL_APPROACH
	// Use a fixed wing approach before detransitioning and landing vertically.
	NAV_VTOL_LAND_OPTIONS_FW_APPROACH NAV_VTOL_LAND_OPTIONS = common.NAV_VTOL_LAND_OPTIONS_FW_APPROACH
)
