//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Basic component information data. Should be requested using MAV_CMD_REQUEST_MESSAGE on startup, or when required.
type MessageComponentInformationBasic = common.MessageComponentInformationBasic
