//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/bluenviron/gomavlib/v4/pkg/dialects/common"
)

// Status of the Iridium SBD link.
type MessageIsbdLinkStatus = common.MessageIsbdLinkStatus
