//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// File transfer protocol message: https://mavlink.io/en/services/ftp.html.
type MessageFileTransferProtocol = common.MessageFileTransferProtocol
