//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Status of geo-fencing. Sent in extended status stream when fencing enabled.
type MessageFenceStatus = common.MessageFenceStatus
