//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Reply to LOG_REQUEST_DATA
type MessageLogData = common.MessageLogData
