//autogenerated:yes
//nolint:revive,misspell,govet,lll
package matrixpilot

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// The autopilot is requesting a resource (file, binary, other type of data)
type MessageResourceRequest = common.MessageResourceRequest
