//autogenerated:yes
//nolint:revive,govet,errcheck
package icarous_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	dialectpkg "github.com/bluenviron/gomavlib/v4/pkg/dialects/icarous"
)

func TestEnum_ICAROUS_TRACK_BAND_TYPES(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e dialectpkg.ICAROUS_TRACK_BAND_TYPES
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := dialectpkg.ICAROUS_TRACK_BAND_TYPE_NONE.MarshalText()
		require.NoError(t, err)

		var dec dialectpkg.ICAROUS_TRACK_BAND_TYPES
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, dialectpkg.ICAROUS_TRACK_BAND_TYPE_NONE, dec)
	})
}
