//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

type HEADING_TYPE = ardupilotmega.HEADING_TYPE

const (
	HEADING_TYPE_COURSE_OVER_GROUND HEADING_TYPE = ardupilotmega.HEADING_TYPE_COURSE_OVER_GROUND
	HEADING_TYPE_HEADING            HEADING_TYPE = ardupilotmega.HEADING_TYPE_HEADING
)
