//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Bus types for device operations.
type DEVICE_OP_BUSTYPE = ardupilotmega.DEVICE_OP_BUSTYPE

const (
	// I2C Device operation.
	DEVICE_OP_BUSTYPE_I2C DEVICE_OP_BUSTYPE = ardupilotmega.DEVICE_OP_BUSTYPE_I2C
	// SPI Device operation.
	DEVICE_OP_BUSTYPE_SPI DEVICE_OP_BUSTYPE = ardupilotmega.DEVICE_OP_BUSTYPE_SPI
)
