//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/csairlink"
)

type AIRLINK_EYE_TURN_INIT_TYPE = csairlink.AIRLINK_EYE_TURN_INIT_TYPE

const (
	AIRLINK_TURN_INIT_START AIRLINK_EYE_TURN_INIT_TYPE = csairlink.AIRLINK_TURN_INIT_START
	AIRLINK_TURN_INIT_OK    AIRLINK_EYE_TURN_INIT_TYPE = csairlink.AIRLINK_TURN_INIT_OK
	AIRLINK_TURN_INIT_BAD   AIRLINK_EYE_TURN_INIT_TYPE = csairlink.AIRLINK_TURN_INIT_BAD
)
