//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// The global position resulting from GPS and sensor fusion.
type MessageUtmGlobalPosition = common.MessageUtmGlobalPosition
