//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Current motion information from a designated system
type MessageFollowTarget = common.MessageFollowTarget
