//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// Offsets and calibrations values for hardware sensors. This makes it easier to debug the calibration process.
type MessageSensorOffsets = ardupilotmega.MessageSensorOffsets
