//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// EKF Status message including flags and variances.
type MessageEkfStatusReport = ardupilotmega.MessageEkfStatusReport
