//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// RPM sensor data message.
type MessageRawRpm = common.MessageRawRpm
