//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Large debug/prototyping array. The message uses the maximum available payload for data. The array_id and name fields are used to discriminate between messages in code and in user interfaces (respectively). Do not use in production code.
type MessageDebugFloatArray = common.MessageDebugFloatArray
