//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/csairlink"
)

// A package with information about the hole punching status. It is used for constant sending to avoid NAT closing timeout.
type MessageAirlinkEyeHp = csairlink.MessageAirlinkEyeHp
