//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// Read registers for a device.
type MessageDeviceOpRead = ardupilotmega.MessageDeviceOpRead
