//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Information about video stream. It may be requested using MAV_CMD_REQUEST_MESSAGE, where param2 indicates the video stream id: 0 for all streams, 1 for first, 2 for second, etc.
type MessageVideoStreamInformation = common.MessageVideoStreamInformation
