//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// RPM sensor output.
type MessageRpm = ardupilotmega.MessageRpm
