//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Request a chunk of a log
type MessageLogRequestData = common.MessageLogRequestData
