//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// Read a configured an OSD parameter slot.
type MessageOsdParamShowConfig = ardupilotmega.MessageOsdParamShowConfig
