//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Data for injecting into the onboard GPS (used for DGPS)
type MessageGpsInjectData = common.MessageGpsInjectData
