//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Metrics typically displayed on a HUD for fixed wing aircraft.
type MessageVfrHud = common.MessageVfrHud
