//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/ardupilotmega"
)

// Status of secondary AHRS filter if available.
type MessageAhrs2 = ardupilotmega.MessageAhrs2
