//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// Control vehicle LEDs.
type MessageLedControl = ardupilotmega.MessageLedControl
