//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/csairlink"
)

// Response information about the connected device
type MessageAirlinkEyeGsHolePushResponse = csairlink.MessageAirlinkEyeGsHolePushResponse
