//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Message to control a camera mount, directional antenna, etc.
type MessageMountControl = ardupilotmega.MessageMountControl
