//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Stop log transfer and resume normal logging
type MessageLogRequestEnd = common.MessageLogRequestEnd
