//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Camera vision based attitude and position deltas.
type MessageVisionPositionDelta = ardupilotmega.MessageVisionPositionDelta
