//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Request a GOPRO_COMMAND response from the GoPro.
type MessageGoproGetRequest = ardupilotmega.MessageGoproGetRequest
