//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/ardupilotmega"
)

// Set the magnetometer offsets
type MessageSetMagOffsets = ardupilotmega.MessageSetMagOffsets
