//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Local position/attitude estimate from a vision source.
type MessageVisionPositionEstimate = common.MessageVisionPositionEstimate
