//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Motion capture attitude and position
type MessageAttPosMocap = common.MessageAttPosMocap
