//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// 3 axis gimbal measurements.
type MessageGimbalReport = ardupilotmega.MessageGimbalReport
