//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/ardupilotmega"
)

// Message to configure a camera mount, directional antenna, etc.
type MessageMountConfigure = ardupilotmega.MessageMountConfigure
