//autogenerated:yes
//nolint:revive,misspell,govet,lll
package storm32

// Offsets and calibrations values for hardware sensors. This makes it easier to debug the calibration process.
type MessageSensorOffsets struct {
	// Magnetometer X offset.
	MagOfsX int16
	// Magnetometer Y offset.
	MagOfsY int16
	// Magnetometer Z offset.
	MagOfsZ int16
	// Magnetic declination.
	MagDeclination float32
	// Raw pressure from barometer.
	RawPress int32
	// Raw temperature from barometer.
	RawTemp int32
	// Gyro X calibration.
	GyroCalX float32
	// Gyro Y calibration.
	GyroCalY float32
	// Gyro Z calibration.
	GyroCalZ float32
	// Accel X calibration.
	AccelCalX float32
	// Accel Y calibration.
	AccelCalY float32
	// Accel Z calibration.
	AccelCalZ float32
}

// GetID implements the msg.Message interface.
func (*MessageSensorOffsets) GetID() uint32 {
	return 150
}
