//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package pythonarraytest

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Specifies the conditions under which the MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN command should be accepted.
type REBOOT_SHUTDOWN_CONDITIONS = common.REBOOT_SHUTDOWN_CONDITIONS

const (
	// Reboot/Shutdown only if allowed by safety checks, such as being landed.
	REBOOT_SHUTDOWN_CONDITIONS_SAFETY_INTERLOCKED REBOOT_SHUTDOWN_CONDITIONS = common.REBOOT_SHUTDOWN_CONDITIONS_SAFETY_INTERLOCKED
	// Force reboot/shutdown of the autopilot/component regardless of system state.
	REBOOT_SHUTDOWN_CONDITIONS_FORCE REBOOT_SHUTDOWN_CONDITIONS = common.REBOOT_SHUTDOWN_CONDITIONS_FORCE
)
