//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Message appropriate for high latency connections like Iridium
type MessageHighLatency = common.MessageHighLatency
