//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// The autopilot is requesting a resource (file, binary, other type of data)
type MessageResourceRequest = common.MessageResourceRequest
