//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/chrisdalke/gomavlib/v3/pkg/dialects/common"
)

// Setpoint in roll, pitch, yaw and thrust from the operator
type MessageManualSetpoint = common.MessageManualSetpoint
