//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/bluenviron/gomavlib/v3/pkg/dialects/common"
)

// Information about a potential collision
type MessageCollision = common.MessageCollision
