//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/aler9/gomavlib/pkg/dialects/common"
)

// Hardware status sent by an onboard computer.
type MessageOnboardComputerStatus = common.MessageOnboardComputerStatus
