//autogenerated:yes
//nolint:revive,misspell,govet,lll
package pythonarraytest

import (
	"github.com/bluenviron/gomavlib/v2/pkg/dialects/common"
)

// Reply to LOG_REQUEST_DATA
type MessageLogData = common.MessageLogData
