//autogenerated:yes
//nolint:golint,misspell,govet,lll
package pythonarraytest

// Array test #0.
type MessageArrayTest_0 struct {
	// Stub field
	V1 uint8
	// Value array
	ArI8 [4]int8
	// Value array
	ArU8 [4]uint8
	// Value array
	ArU16 [4]uint16
	// Value array
	ArU32 [4]uint32
}

// GetID implements the msg.Message interface.
func (*MessageArrayTest_0) GetID() uint32 {
	return 17150
}
